### ISSUE TITLE
Running into a deploy issue

### ISSUE THREAD

**Issue by aarongustafson** [IAmAdamTaylor/AKApartNewsReader#1]
```
Invalid path for filesystem 'D:/home/site/repository/node_modules/gulp-autoprefixer/node_modules/gulp-util/node_modules/dateformat/node_modules/meow/node_modules/normalize-package-data/node_modules/validate-npm-package-license/node_modules/spdx-correct/node_modules/spdx-license-ids/.gitattributes': The data area passed to a system call is too small.\r\n
```

**Comment by IAmAdamTaylor** [comment]
The issue seems to be contained to the node_modules folder which the project doesn't require to run. I've removed those from the repo - please try again?

**Comment by aarongustafson** [comment]
Reloaded, but I don’t know if this is right: https://byte-sized-news-10kapart2016.azurewebsites.net/

Seems to be missing styles entirely.

**Comment by IAmAdamTaylor** [comment]
Apologies Aaron. As per best practices I had ignored the generated files which means you didn't have them. Added those now and tested that everything is working by downloading and setting up a fresh copy myself.

**Comment by aarongustafson** [comment]
I’ll pull as well

**Comment by aarongustafson** [comment]
Yay! https://byte-sized-news-10kapart2016.azurewebsites.net/

**Comment by IAmAdamTaylor** [comment]
Thanks Aaron!
